name: geogerenv
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - pip
  - nodejs
  - panel
  - datashader
  - holoviews
  - hvplot
  - param
  - geoviews
  - geoviews-core
  - pyviz_comms
  - holoviz
  - contrib_colormaps
  - colorcet
  - parambokeh
  - paramnb
  - pyct
  - spatialpandas
  - rasterio
#  - pip:                            # Packages installed from PyPI
#    - requests==2.21.0