name: geogerenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - folium 
  - pandas
  - jupyterlab  
  - rasterio 
  - matplotlib 
  - pyproj 
  - shapely
  - fiona 
  - scikit-learn 
  - geopandas
  - panel 
  - rtree 
  - geojson 
  - bokeh 
  - rise 
  - xarray
  - geopy
  - seaborn
  - pysal
  - dask
  - pip
#  - pip:                            # Packages installed from PyPI
#    - requests==2.21.0